name: Run Laravel Pint and Build PHP

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pint:
    uses: ua-app-images/build-laravel-app-image/.github/workflows/pint-fix.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
    secrets: inherit

  build-php:
    if: >
      always() &&
      needs.run-pint.result == 'success' &&
      (github.ref_name == 'test' || github.ref_name == 'prod')
    needs: run-pint
    uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
    secrets: inherit
