name: Run Laravel Pint and Build PHP

on:
  push:
  pull_request_target:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pint:
    uses: ua-app-images/build-laravel-app-image/.github/workflows/pint-fix.yml@test
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.base_ref || github.ref_name }}
    secrets: inherit

  build-php:
    needs: run-pint
    uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@test
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.base_ref || github.ref_name }}
    secrets: inherit