name: Build PHP

on:
  workflow_run:
    workflows: ["Run Laravel Pint"]  # Must exactly match the `name:` in call-pint.yml
    types:
      - completed

permissions:
  contents: read

jobs:
  trigger-deployment:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'test' || github.event.workflow_run.head_branch == 'prod')
    uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@pint
    with:
      repository: ${{ github.event.workflow_run.head_repository.full_name }}
      branch: ${{ github.event.workflow_run.head_branch }}
    secrets: inherit
